### ISSUE TITLE
Invalid directory entry: .DS_Store in ./world/datapacks/rotten-flesh-to-leather_1.21.

### ISSUE THREAD

**Issue by Smolwong** [Smolwong/Smolcraft#12]
[11:20:39 ERROR]: Invalid directory entry: .DS_Store in ./world/datapacks/rotten-flesh-to-leather_1.21.
java.nio.file.NotDirectoryException: .DS_Store
        at net.minecraft.server.packs.PathPackResources.getNamespaces(PathPackResources.java:108) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.packs.resources.MultiPackResourceManager.lambda$new$0(MultiPackResourceManager.java:27) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at net.minecraft.server.packs.resources.MultiPackResourceManager.<init>(MultiPackResourceManager.java:27) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.WorldLoader$PackConfig.createResourceManager(WorldLoader.java:107) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.WorldLoader.load(WorldLoader.java:32) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.Main.lambda$main$1(Main.java:277) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.Util.blockUntilDone(Util.java:892) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.Util.blockUntilDone(Util.java:887) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.Main.main(Main.java:276) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at org.bukkit.craftbukkit.Main.main(Main.java:295) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:20:39 ERROR]: Invalid directory entry: .DS_Store in ./world/datapacks/rotten-flesh-to-leather_1.21.
java.nio.file.NotDirectoryException: .DS_Store
        at net.minecraft.server.packs.PathPackResources.getNamespaces(PathPackResources.java:108) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.packs.resources.MultiPackResourceManager.<init>(MultiPackResourceManager.java:31) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.WorldLoader$PackConfig.createResourceManager(WorldLoader.java:107) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.WorldLoader.load(WorldLoader.java:32) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.Main.lambda$main$1(Main.java:277) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.Util.blockUntilDone(Util.java:892) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.Util.blockUntilDone(Util.java:887) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at net.minecraft.server.Main.main(Main.java:276) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at org.bukkit.craftbukkit.Main.main(Main.java:295) ~[purpur-1.21.jar:1.21-2275-82ccc76]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Smolwong** [comment]
Bad developer left MacOS files.
