### ISSUE TITLE
LibertyBans config issue

### ISSUE THREAD

**Issue by Smolwong** [Smolwong/Smolcraft#14]
[11:21:42 WARN]: [space.arim.libertybans.core.config.ConfigHolder] The values in your configuration are invalid. Please correct the issue and run /libertybans reload. For now, the default configuration will be used.
space.arim.dazzleconf.error.BadValueException: For key durations-to-supply:
fourh must be a valid duration
        at LibertyBans-ClassLoader/space.arim.dazzleconf.error.BadValueException$Builder.build(BadValueException.java:95) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.config.ParsedDuration$Serializer.deserialise(ParsedDuration.java:91) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.config.ParsedDuration$Serializer.deserialise(ParsedDuration.java:79) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.fromSerialiser(FlexibleTypeImpl.java:332) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getObject0(FlexibleTypeImpl.java:319) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getObject(FlexibleTypeImpl.java:275) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.Composition.lambda$getCollection$1(Composition.java:106) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getCollection0(FlexibleTypeImpl.java:235) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getSet(FlexibleTypeImpl.java:206) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.Composition.getCollectionUsing(Composition.java:126) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.Composition.getCollection(Composition.java:110) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:68) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createFromProcessor(ProcessorBase.java:160) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.MapProcessor.createChildConfig(MapProcessor.java:60) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createNested(ProcessorBase.java:156) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:61) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createFromProcessor(ProcessorBase.java:160) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.MapProcessor.createChildConfig(MapProcessor.java:60) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createNested(ProcessorBase.java:156) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:61) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createFromProcessor(ProcessorBase.java:160) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.MapProcessor.createChildConfig(MapProcessor.java:60) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createNested(ProcessorBase.java:156) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:61) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.factory.ConfigurationFormatFactory.fromRawMap(ConfigurationFormatFactory.java:174) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.factory.ConfigurationFormatFactory.load(ConfigurationFormatFactory.java:126) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.factory.DelegatingConfigurationFactory.load(DelegatingConfigurationFactory.java:57) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.dazzleconf.factory.AbstractConfigurationFactory.load(AbstractConfigurationFactory.java:42) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.config.ConfigHolder.loadFromPath(ConfigHolder.java:116) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.config.ConfigHolder.lambda$reload$0(ConfigHolder.java:87) ~[LibertyBans-ClassLoader:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by Smolwong** [comment]
Reworking moderation tools, switching to Litebans to replace Libertybans.
